apiVersion: v1
kind: Secret
metadata:
  name: vidjot-secrets
type: Opaque
data:
  PORT: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: vidjot-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vidjot
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vidjot-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: vidjot-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: vidjot-service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vidjot-deployment
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vidjot
    spec:
      containers:
        - image: sonujithu/vidjot
          imagePullPolicy: Always
          name: vidjot
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: vidjot-secrets
